spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/strategyreportsdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
